version: '3.8'

services:
  # Nginx Load Balancer
  load_balancer:
    image: nginx:latest
    container_name: nginx_load_balancer
    volumes:
      - ./nginx-load-balancer.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose load balancer on port 80
    depends_on:
      - web1
      - web2
      - web3

  # Web Server 1
  web1:
    image: nginx:latest
    container_name: nginx_web1
    volumes:
      - ./web1:/usr/share/nginx/html  # Mount custom content for server
    expose:
      - "80"  # Internal port for load balancer communication

  # Web Server 2
  web2:
    image: nginx:latest
    container_name: nginx_web2
    volumes:
      - ./web2:/usr/share/nginx/html
    expose:
      - "80"

  # Web Server 3
  web3:
    image: nginx:latest
    container_name: nginx_web3
    volumes:
      - ./web3:/usr/share/nginx/html
    expose:
      - "80"
